### ISSUE TITLE
Room Blockout Tool

### ISSUE THREAD

**Issue by charlie2099** [HoppiStudio/HauntMyHouse#1]
**Is your feature request related to a problem? Please describe.**
The current room blockout system SHOULD work but doesn't (Pending further investigation to provide more context).

**Describe the solution you'd like**
The player should be able to blockout a mesh for furniture and items in the player's play space using a paint-like tool. These meshes will be used to determine obstacles in the play space as well as acting as potential spawn points for candles, matchboxes, lighters, etc

**Describe alternatives you've considered**
N/A

**Additional context**
The blockout tool should be usable pre-game only

**Comment by Ahillman2000** [comment]
Either needs to be fixed ASAP or completely redone in a different way so that it works.

**Comment by Ahillman2000** [comment]
needs to be integrated with the XRInteraction toolkit for trigger + requires world position of controller

- requires vertices to be created in specific order of positioning
