### ISSUE TITLE
Proper win and lose conditions (with UI screens)

### ISSUE THREAD

**Issue by Ahillman2000** [HoppiStudio/HauntMyHouse#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vincentvason** [comment]
Update /w @int-Kaan:
- HP and Intensity Level
- Win Condition: Banish three ghosts.
- Lose Condition: When HP reaches zero.

**Comment by vincentvason** [comment]
Expected Finish on 10 march
