### ISSUE TITLE
Complete Candle Puzzle

### ISSUE THREAD

**Issue by Ahillman2000** [HoppiStudio/HauntMyHouse#25]
**Is your feature request related to a problem? Please describe.**
Current version of the candle puzzle is unclear and can be made to require more inter-player interaction.

**Describe the solution you'd like**
- A board with chemical symbols and the colours they produce, connected with lines. The colours they produce are not in the same order as the chemical list so that players have to use the lines to find.
- Objects that change the colour of the matchstick
- podiums of a range of colours

**Comment by charlie2099** [comment]
Completed upon merge f2b0b51ed44ab52f542a2ed5d2a70e6472d89080
