### ISSUE TITLE
Candle Flame Doesnt Work

### ISSUE THREAD

**Issue by int-Kaan** [HoppiStudio/HauntMyHouse#28]
**Describe the bug**
Candle flame doesn't work when you collide the matchstick with the matchbox 

**Expected behavior**
Candle flame must work properly.

**Comment by charlie2099** [comment]
Matchbox currently checks for an OVR input. Needs to check for a input from the newly implemented XR interaction system.

**Comment by charlie2099** [comment]
Fixed in commit ca0d07f6ee9ba17b2f9ff5ef81ff44efa8e57081
